#! /bin/sh
xmodmap -e "keycode 134 = NoSymbol"

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII #IX X

bspc config border_width         1
bspc config window_gap           8

#bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false

# Mouse suport resize
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
#bspc config pointer_action3 resize_corner

#Start programs
cd $HOME/.config/bspwm/ && ./startPrograms.sh &
